name: Heart

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          options: |
            args:
              - --no-sandbox
              - --disable-dev-shm-usage

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install software
        run: |
          cd testes
          sudo apt-get install -y chromium-browser
        
      - name: Install the necessary packages
        run: |
          cd testes
          pip install requests webdriver-manager selenium pytest
        
      - name: Run the PytTest script
        run: |
          cd testes
          pytest -rA

      - name: Build React app
        run: |
          cd frontend
          npm ci
          npm run build
