name: Heart

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          options: |
            args:
              - --no-sandbox
              - --disable-dev-shm-usage

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install software
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          LATEST_CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          curl -o /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
        
      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Install necessary packages
        run: |
          pip install requests selenium pytest

      - name: Run the PyTest script
        run: |
          cd testes
          pytest -rA


      - name: Build React app
        run: |
          cd frontend
          npm ci
          npm run build
